### ISSUE TITLE
Insulting invisnik in readme

### ISSUE THREAD

**Issue by Gummibeer** [kanalumaddela/laravel-steam-login#11]
I don't think that insulting another developer  ( @invisnik ) isn't the right content for a readme file - especially in the **Credits** section.

> https://github.com/invisnik/laravel-steam-auth (Getting me to create a laravel steam auth that isn't shit, your code totally doesn't look like Ehesp's you cuck. For others reading this compare the code, invisnik can't even give proper credit)

**Comment by Gummibeer** [comment]
@handsomematt what do you mean?

**Comment by handsomematt** [comment]
sorry I typoed

**Comment by Salakar** [comment]
![nom](https://media.giphy.com/media/128UMaujdjX7Pi/giphy.gif)
