### ISSUE TITLE
Issue with Laravel 7 & Laragon

### ISSUE THREAD

**Issue by FoksVHox** [kanalumaddela/laravel-steam-login#57]
Hello,
I'm trying to install this, but I'm getting an error when trying to.
![image](https://user-images.githubusercontent.com/37844753/86531196-7f2e6780-bebf-11ea-8029-deb1e205f954.png)

I've ext-gmp enabled in my PHP, so I'm not so sure why this happens..

**Comment by kanalumaddela** [comment]
How have you enabled the extension in your php.ini? Can you paste the line here?

**Comment by FoksVHox** [comment]
Found out that it was my composer that was out of date. Reinstalling composer fixes it.
