### ISSUE TITLE
"could not find driver"

### ISSUE THREAD

**Issue by JoshJOkayguy** [kanalumaddela/laravel-steam-login#64]
I'm fairly certain (and yet uncertain at the same time, I am extremely new to using Laravel so I'm not sure what I could have done) this is an installation issue, and therefore something **I** did wrong, so I must apologize in advance. I followed the instructions, and even after doing some manual editing to the SteamLoginController (App\User gave me an error that said it "wasn't found", so I used "App\Models\User" which seemed to fix the issue), I landed upon a seemingly database related issue.

The setup says nothing about a specific database schema, although possibly that's implied and I'm too dense to realize that. That being said, after attempting to authorize I receive the QueryException "could not find driver (SQL: select * from `users` where `steam_account_id` = 393058422 limit 1)".

Again, I really apologize for my lack of understanding however I'm honestly not certain what to do about this. If you believe there's something I need to know/learn before using this repo, I'd love it if you'd direct me to that.

I have edited the .env file to the proper database settings, I believe.

**Comment by JoshJOkayguy** [comment]
Figured I'd just use socialite instead.

**Comment by kanalumaddela** [comment]
> The setup says nothing about a specific database schema

The **_assumption_** is defined the example code both in the docs and in the readme is that your User model has a `steam_account_id` column the users table.

From the [2.x docs](https://github.com/kanalumaddela/laravel-steam-login/wiki/2.x-Usage-Laravel)
![image](https://user-images.githubusercontent.com/14265751/122686927-c5203080-d1e1-11eb-8a7c-4005e5c8daa0.png)


From the [README](https://github.com/kanalumaddela/laravel-steam-login/blob/master/README.md)
![image](https://user-images.githubusercontent.com/14265751/122686896-a1f58100-d1e1-11eb-83e8-7d605a0a5bfe.png)


> (App\User gave me an error that said it "wasn't found", so I used "App\Models\User" which seemed to fix the issue)

None of the examples in the docs are based for **Laravel 8.x**. Laravel 8.x introduced the `Models/` directory hence the new location of the `User` model. The readme however was updated a while back to be more general and open to reduce any version specific code.
